### ISSUE TITLE
ili9486 and nodemcu

### ISSUE THREAD

**Issue by joe318** [Bodmer/TFT_eSPI#317]
Hello mr Bodmer,

I buy the 3.5 inch rpi version, i think it's the ili9486, not sure at 100% but 99%.
I try manyyyyy different configurations like reduce the spi, i try allll the setup ili9486, i disconnect the touch, and disconnect and connect everything maybe 10 times, but i always have the same result, i put you pics for you see.
![img_2413](https://user-images.githubusercontent.com/38740665/53288624-5c942680-3782-11e9-8b8c-500814b97a2e.JPG)
![img_2414](https://user-images.githubusercontent.com/38740665/53288625-5c942680-3782-11e9-9ea8-9969d7d3db35.JPG)
![img_2415](https://user-images.githubusercontent.com/38740665/53288626-5c942680-3782-11e9-955c-c279a1d1cbcc.JPG)

Can i have help to find where is my problem?
Regards,

**Comment by joe318** [comment]
Just another test, when i choose Setup6_RPi_Wr_ILI9486.h, the fonts work better, not good too but better.

**Comment by joe318** [comment]
Another important detail, its a waveshare rev A ver 3 for rpi

**Comment by joe318** [comment]
after another tests, work well with raspberry and esp32 but with schreibfaul1 library, i want put work with the 8266 :(

**Comment by Bodmer** [comment]
Try the latest version of the library, there was a bug associated with the RPi display that shloud be fixed in the latest version.

**Comment by joe318** [comment]
oh cool, i'm waitingggggg lol, when you think the library can be ready?
kiss

**Comment by Bodmer** [comment]
The library was updated 1 week ago in response to issue #310 which looks like the same problem. Download the latest from Github and try it.

**Comment by joe318** [comment]
Hello, was try with one wemos and nodemcu, esp8266 but always the same problem, i try many things like what they do in the issue 310 but without success :(

**Comment by joe318** [comment]
The most strange it's the better solution i found (still not perfect) it's when i use yout setup6, can see the text nice but not the background with the rainbow example for example.

**Comment by joe318** [comment]
ok i found why, he work well with the SPI_FREQUENCY  10000000 shit it's slow no?

**Comment by Bodmer** [comment]
Thanks for reporting the solution. You may find it works OK at 16MHz, try:

SPI_FREQUENCY 16000000

**Comment by joe318** [comment]
hello, tested now at 16000000, better than 20 but not perfect

**Comment by joe318** [comment]
i test now at 15, look working, need try more

**Comment by joe318** [comment]
Mr bodmer, just for help people, the 4inch waveshare for uno work with my nodemcu with the spi speed at 15
if can help pp
